name: e2e-tests
on: [push, pull_request]
jobs:
    cypress-run:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                containers: [1, 2, 3]
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Cypress run
              uses: cypress-io/github-action@v5
              with:
                  command: npx cypress run
                  browser: chrome
              env:
                  SPLIT: ${{ strategy.job-total }}
                  SPLIT_INDEX: ${{ strategy.job-index }}
            - name: for screenshots if any
              if: failure()
              uses: actions/upload-artifact@v2
              with:
               name: screenshots
               path: cypress/screenshots/**/**/*.png
               retention-days: 5
            - name: for videos if any
              if: always()
              uses: actions/upload-artifact@v2
              with:
               name: videos
               path: cypress/videos/**/*.mp4
               retention-days: 5
