name: e2e-tests
on: [push, pull_request]
jobs:
  test:
    # https://github.com/bahmutov/cypress-workflows
    uses: bahmutov/cypress-workflows/.github/workflows/split.yml@v1.9.10
    with:
      n: 4
      browser: chrome
      headed: true
      marge: true
      